openapi: 3.0.0
info:
  title: WUEST API
  version: 1.0.0

servers:
  - url: /v1

paths:
  /healthz:
    get:
      summary: Healthcheck endpoint.
      responses:
        '200':
          description: 'Returns a plain OK to indicate the API is running'
          content:
            text/plain:
              schema:
                type: string
